
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations = {
  en: {
    "app.title": "RealCity Architect",
    "app.lobby": "PROJECT_LOBBY",
    "app.logic_active": "LOGIC_CORE_ACTIVE",
    "app.editor": "Editor",
    "app.simulate": "Simulate",
    "app.save_json": "EXPORT JSON",
    "app.sync_db": "SYNC DB",
    "app.export_title": "EXPORT LOGIC",
    "app.export_desc": "Copy this code to share the flow with others.",
    "app.import_title": "IMPORT LOGIC",
    "app.import_desc": "Paste the logic code below to import the flow.",
    "app.copy": "COPY TO CLIPBOARD",
    "app.copied": "COPIED!",
    "app.import_action": "IMPORT DATA",
    "app.invalid_json": "The provided data is not a valid JSON.",
    "app.import_success": "Project imported successfully.",
    "app.confirm_delete": "WARNING: Confirm deletion of logic flow? This action is irreversible.",
    "app.ready_sync": "Ready for Database Sync",
    
    "dashboard.groups": "Groups",
    "dashboard.all_flows": "All Flows",
    "dashboard.new_group": "+ New Group",
    "dashboard.search_placeholder": "Filter by name...",
    "dashboard.new_flow": "+ New Flow",
    "dashboard.import_json": "IMPORT JSON",
    "dashboard.move_to": "Move To",
    "dashboard.nodes": "NODES",
    "dashboard.modified": "MODIFIED",
    "dashboard.empty_state": "No flows found in this sector",
    "dashboard.modal.title": "Initialize Sequence",
    "dashboard.modal.project_name": "Project Name",
    "dashboard.modal.target_group": "Target Group",
    "dashboard.modal.cancel": "Cancel",
    "dashboard.modal.create": "Create",
    "dashboard.modal.delete_flow.title": "Delete Flow?",
    "dashboard.modal.delete_flow.text": "Are you sure you want to delete this interaction flow? This action cannot be undone.",
    "dashboard.modal.delete_group.title": "Delete Group?",
    "dashboard.modal.delete_group.text": "Are you sure you want to delete the group \"{name}\"? All projects in this group will be moved to \"General\".",
    "dashboard.modal.delete": "Delete",
    "dashboard.confirm_delete_group": "Delete group \"{name}\"? Projects inside will be moved to General.",
    "dashboard.error_delete_general": "Cannot delete default 'General' group.",
    "dashboard.group_placeholder": "Group Name...",
    
    "editor.properties": "PROPERTIES",
    "editor.npc_id": "NPC ID",
    "editor.text_buffer": "Text Buffer",
    "editor.responses": "Responses",
    "editor.add": "+ ADD",
    "editor.variable_key": "Variable Key",
    "editor.operator": "Operator",
    "editor.value_check": "Check Value",
    "editor.value_set": "Set Value To",
    "editor.event_name": "Event Name",
    "editor.event_payload": "Event Payload (Variable/Data)",
    "editor.is_server_event": "Trigger Server-Side",
    "editor.destroy_node": "DESTROY NODE",
    "editor.add_logic_block": "Add Logic Block",
    "editor.node.start": "BEGIN FLOW",
    "editor.node.end": "TERMINATE",
    "editor.node.set_variable": "SET",
    "editor.node.trigger": "TRIGGER",
    "editor.node.if": "IF",
    "editor.node.true": "TRUE",
    "editor.node.false": "FALSE",
    "editor.type_text": "Enter text...",
    "editor.type_next": "Next",
    "editor.type_option": "New Option",
    "editor.no_props": "No specific properties for this node type.",
    "editor.undo": "UNDO",
    "editor.redo": "REDO",
    "editor.reset_view": "RESET VIEW",
    "editor.npc_model": "NPC MODEL",
    "editor.coords": "COORDS (X Y Z W)",
    "editor.use_my_position": "USE MY POSITION",
    "editor.coord_w_heading": "W (heading)",
    "editor.op_equals": "== Equals",
    "editor.op_not_equals": "!= Not Equals",
    "editor.op_greater": "> Greater Than",
    "editor.op_less": "< Less Than",
    "editor.op_greater_eq": ">= Greater/Eq",
    "editor.op_less_eq": "<= Less/Eq",
    "dashboard.delete_group_btn": "Delete Group",
    "dashboard.delete_btn": "Delete",
    "runtime.header": "INTERACTION",
    "runtime.npc_fallback": "NPC",
    "runtime.waiting_event": "Waiting for event...",
    "runtime.navigate": "NAVIGATE",
    "runtime.select": "SELECT",
    "runtime.leave": "LEAVE",

    "editor.item_name": "Item Name",
    "editor.item_count": "Count",
    "editor.money_type": "Money Type",
    "editor.money_amount": "Amount",
    "editor.idle_animation": "Idle Animation",
    "editor.idle_animation_hint": "Animation the NPC plays while idle (before interaction)",
    "editor.anim_dict_placeholder": "e.g. amb@world_human_clipboard@male@base",
    "editor.anim_name_placeholder": "e.g. base",
    "editor.anim_dict": "Anim Dict",
    "editor.anim_name": "Anim Name",
    "editor.anim_target": "Target",
    "editor.anim_target_npc": "NPC",
    "editor.anim_target_player": "Player",
    "editor.anim_duration": "Duration (ms)",
    "editor.wait_duration": "Wait Duration (ms)",
    "editor.random_outputs": "Outputs",
    "editor.random_weight": "Weight %",
    "editor.teleport_coords": "Teleport Coords (X Y Z W)",
    "editor.new_model": "New NPC Model",
    "editor.new_anim_dict": "New Anim Dict",
    "editor.new_anim_name": "New Anim Name",
    "editor.sound_name": "Sound Name",
    "editor.sound_volume": "Volume (0-100)",
    "editor.dialogue_anim": "Node Animation (optional)",
    "editor.node.dialogue": "DIALOGUE",
    "editor.node.condition": "CONDITION",
    "editor.node.event": "EVENT",
    "editor.node.give_item": "GIVE ITEM",
    "editor.node.remove_item": "REMOVE ITEM",
    "editor.node.give_money": "GIVE MONEY",
    "editor.node.remove_money": "REMOVE MONEY",
    "editor.node.animation": "ANIMATION",
    "editor.node.wait": "WAIT",
    "editor.node.random": "RANDOM",
    "editor.node.teleport": "TELEPORT",
    "editor.node.npc_change": "NPC CHANGE",
    "editor.node.sound": "SOUND",

    "editor.cat_flow": "Flow",
    "editor.cat_dialogue": "Dialogue",
    "editor.cat_logic": "Logic",
    "editor.cat_economy": "Economy",
    "editor.cat_effects": "Effects",
    "editor.search_nodes": "Search",
    "editor.hint_pan": "Pan canvas",
    "editor.hint_search": "Search nodes",
    "editor.hint_delete": "Delete selected",
    "editor.hint_duplicate": "Duplicate",
    "editor.hint_auto_layout": "Auto layout",
    "editor.auto_layout": "Auto Layout",
    "editor.node_count": "nodes",
    "editor.conn_count": "links",
    "editor.palette_placeholder": "Search for a node...",
    "editor.palette_empty": "No nodes match your search",
    "editor.palette_add": "Add",
    "editor.palette_close": "Close",
    "editor.fit_view": "Fit to View",
    "editor.duplicate": "Duplicate",
    "editor.event_server": "Server-side",
    "editor.event_payload": "Payload",

    "simulator.start": "Start Simulation",
    "simulator.live_feed": "Live Feed",
    "simulator.system": "SYSTEM",
    "simulator.memory_debug": "MEMORY STATE (DEBUG)",
    "simulator.no_start_node": "No START node found in graph.",

    "editor.var.cat_memory": "Memory",
    "editor.var.cat_item": "Items",
    "editor.var.cat_money": "Money",
    "editor.var.cat_job": "Job / Group",
    "editor.var.cat_player": "Player",
    "editor.var.raw_key": "KEY",
    "editor.var.custom": "Custom Variable",
    "editor.var.custom_hint": "Variable set by a SET_VARIABLE node (stored in interaction memory).",
    "editor.var.has_item": "Has Item (count)",
    "editor.var.has_item_hint": "Number of this item in the player's inventory. Enter the item name below.",
    "editor.var.money_cash": "Cash",
    "editor.var.money_cash_hint": "Amount of cash the player has on hand.",
    "editor.var.money_bank": "Bank",
    "editor.var.money_bank_hint": "Amount of money in the player's bank account.",
    "editor.var.has_job": "Has Job / Group",
    "editor.var.has_job_hint": "Checks if the player belongs to this job or group. Enter the job name below.",
    "editor.var.player_health": "Health",
    "editor.var.player_health_hint": "Player health (100-200). 100 = dead, 200 = full health.",
    "editor.var.player_armor": "Armor",
    "editor.var.player_armor_hint": "Player armor value (0-100).",
    "editor.var.player_stamina": "Stamina",
    "editor.var.player_stamina_hint": "Sprint stamina remaining (0-100).",
    "editor.var.player_is_dead": "Is Dead",
    "editor.var.player_is_dead_hint": "1 if the player is dead, 0 otherwise.",
    "editor.var.player_is_wanted": "Wanted Level",
    "editor.var.player_is_wanted_hint": "Police wanted level (0-5).",
    "editor.var.player_in_vehicle": "In Vehicle",
    "editor.var.player_in_vehicle_hint": "1 if the player is in any vehicle, 0 otherwise.",
    "editor.var.player_speed": "Speed (km/h)",
    "editor.var.player_speed_hint": "Current movement speed in km/h.",
    "editor.var.player_weapon": "Current Weapon",
    "editor.var.player_weapon_hint": "Weapon hash of the currently equipped weapon.",
    "editor.var.player_is_swimming": "Is Swimming",
    "editor.var.player_is_swimming_hint": "1 if the player is swimming, 0 otherwise.",
    "editor.var.player_is_falling": "Is Falling",
    "editor.var.player_is_falling_hint": "1 if the player is falling, 0 otherwise.",
    "editor.var.player_is_running": "Is Running",
    "editor.var.player_is_running_hint": "1 if the player is running, 0 otherwise.",
    "editor.var.player_name": "Character Name",
    "editor.var.player_name_hint": "Full name (firstname + lastname) from the framework.",
    "editor.var.player_job_name": "Job Name",
    "editor.var.player_job_name_hint": "Name of the player's current job (e.g. 'police', 'mechanic').",
    "editor.var.player_job_grade": "Job Grade",
    "editor.var.player_job_grade_hint": "Numeric grade level of the player's current job.",
    "editor.var.player_gang_name": "Gang Name",
    "editor.var.player_gang_name_hint": "Name of the player's gang (QBCore only, 'none' for ESX).",
    "editor.var.player_citizenid": "Citizen ID",
    "editor.var.player_citizenid_hint": "Unique identifier of the character.",
    "editor.var.player_gender": "Gender",
    "editor.var.player_gender_hint": "0 = male, 1 = female (framework-dependent).",
    "editor.var.player_phone_number": "Phone Number",
    "editor.var.player_phone_number_hint": "Character's phone number.",
    "editor.value_mode_fixed": "Fixed value",
    "editor.value_mode_var": "Compare against another variable"
  },
  es: {
    "app.title": "Arquitecto RealCity",
    "app.lobby": "LOBBY_PROYECTO",
    "app.logic_active": "NUCLEO_LOGICO_ACTIVO",
    "app.editor": "Editor",
    "app.simulate": "Simular",
    "app.save_json": "EXPORTAR JSON",
    "app.sync_db": "SINC DB",
    "app.export_title": "EXPORTAR LÓGICA",
    "app.export_desc": "Copia este código para compartir el flujo con otros.",
    "app.import_title": "IMPORTAR LÓGICA",
    "app.import_desc": "Pega el código de lógica abajo para importar el flujo.",
    "app.copy": "COPIAR AL PORTAPAPELES",
    "app.copied": "¡COPIADO!",
    "app.import_action": "IMPORTAR DATOS",
    "app.invalid_json": "Los datos proporcionados no son un JSON válido.",
    "app.import_success": "Proyecto importado con éxito.",
    "app.confirm_delete": "ADVERTENCIA: ¿Confirmar eliminación del flujo lógico? Esta acción es irreversible.",
    "app.ready_sync": "Listo para Sincronización de Base de Datos",
    
    "dashboard.groups": "Grupos",
    "dashboard.all_flows": "Todos los Flujos",
    "dashboard.new_group": "+ Nuevo Grupo",
    "dashboard.search_placeholder": "Filtrar por nombre...",
    "dashboard.new_flow": "+ Nuevo Flujo",
    "dashboard.import_json": "IMPORTAR JSON",
    "dashboard.move_to": "Mover a",
    "dashboard.nodes": "NODOS",
    "dashboard.modified": "MODIFICADO",
    "dashboard.empty_state": "No se encontraron flujos en este sector",
    "dashboard.modal.title": "Inicializar Secuencia",
    "dashboard.modal.project_name": "Nombre del Proyecto",
    "dashboard.modal.target_group": "Grupo Destino",
    "dashboard.modal.cancel": "Cancelar",
    "dashboard.modal.create": "Crear",
    "dashboard.modal.delete_flow.title": "¿Eliminar Flujo?",
    "dashboard.modal.delete_flow.text": "¿Estás seguro de que quieres eliminar este flujo de interacción? Esta acción no se puede deshacer.",
    "dashboard.modal.delete_group.title": "¿Eliminar Grupo?",
    "dashboard.modal.delete_group.text": "¿Estás seguro de que quieres eliminar el grupo \"{name}\"? Todos los proyectos en este grupo se moverán a \"General\".",
    "dashboard.modal.delete": "Eliminar",
    "dashboard.confirm_delete_group": "¿Eliminar grupo \"{name}\"? Los proyectos dentro se moverán a General.",
    "dashboard.error_delete_general": "No se puede eliminar el grupo por defecto 'General'.",
    "dashboard.group_placeholder": "Nombre del Grupo...",

    "editor.properties": "PROPIEDADES",
    "editor.npc_id": "ID NPC",
    "editor.text_buffer": "Búfer de Texto",
    "editor.responses": "Respuestas",
    "editor.add": "+ AÑADIR",
    "editor.variable_key": "Clave Variable",
    "editor.operator": "Operador",
    "editor.value_check": "Verificar Valor",
    "editor.value_set": "Fijar Valor A",
    "editor.event_name": "Nombre Evento",
    "editor.event_payload": "Carga del Evento (Variable/Datos)",
    "editor.is_server_event": "Activar Lado Servidor",
    "editor.destroy_node": "DESTRUIR NODO",
    "editor.add_logic_block": "Añadir Bloque Lógico",
    "editor.node.start": "INICIAR FLUJO",
    "editor.node.end": "TERMINAR",
    "editor.node.set_variable": "FIJAR",
    "editor.node.trigger": "DISPARAR",
    "editor.node.if": "SI",
    "editor.node.true": "VERDADERO",
    "editor.node.false": "FALSO",
    "editor.type_text": "Introducir texto...",
    "editor.type_next": "Siguiente",
    "editor.type_option": "Nueva Opción",
    "editor.no_props": "No hay propiedades específicas para este tipo de nodo.",
    "editor.undo": "DESHACER",
    "editor.redo": "REHACER",
    "editor.reset_view": "REINICIAR VISTA",
    "editor.npc_model": "MODELO NPC",
    "editor.coords": "COORDS (X Y Z W)",
    "editor.use_my_position": "USAR MI POSICIÓN",
    "editor.coord_w_heading": "W (rumbo)",
    "editor.op_equals": "== Igual",
    "editor.op_not_equals": "!= Diferente",
    "editor.op_greater": "> Mayor que",
    "editor.op_less": "< Menor que",
    "editor.op_greater_eq": ">= Mayor/Igual",
    "editor.op_less_eq": "<= Menor/Igual",
    "dashboard.delete_group_btn": "Eliminar Grupo",
    "dashboard.delete_btn": "Eliminar",
    "runtime.header": "INTERACCIÓN",
    "runtime.npc_fallback": "NPC",
    "runtime.waiting_event": "Esperando evento...",
    "runtime.navigate": "NAVEGAR",
    "runtime.select": "SELECCIONAR",
    "runtime.leave": "SALIR",

    "editor.item_name": "Nombre Ítem",
    "editor.item_count": "Cantidad",
    "editor.money_type": "Tipo de Dinero",
    "editor.money_amount": "Monto",
    "editor.idle_animation": "Animación Idle",
    "editor.idle_animation_hint": "Animación que el NPC reproduce mientras está inactivo (antes de interactuar)",
    "editor.anim_dict_placeholder": "ej. amb@world_human_clipboard@male@base",
    "editor.anim_name_placeholder": "ej. base",
    "editor.anim_dict": "Dict Animación",
    "editor.anim_name": "Nombre Animación",
    "editor.anim_target": "Objetivo",
    "editor.anim_target_npc": "NPC",
    "editor.anim_target_player": "Jugador",
    "editor.anim_duration": "Duración (ms)",
    "editor.wait_duration": "Duración de Espera (ms)",
    "editor.random_outputs": "Salidas",
    "editor.random_weight": "Peso %",
    "editor.teleport_coords": "Coords Teletransporte (X Y Z W)",
    "editor.new_model": "Nuevo Modelo NPC",
    "editor.new_anim_dict": "Nuevo Dict Animación",
    "editor.new_anim_name": "Nuevo Nombre Animación",
    "editor.sound_name": "Nombre Sonido",
    "editor.sound_volume": "Volumen (0-100)",
    "editor.dialogue_anim": "Animación del Nodo (opcional)",
    "editor.node.dialogue": "DIÁLOGO",
    "editor.node.condition": "CONDICIÓN",
    "editor.node.event": "EVENTO",
    "editor.node.give_item": "DAR ÍTEM",
    "editor.node.remove_item": "QUITAR ÍTEM",
    "editor.node.give_money": "DAR DINERO",
    "editor.node.remove_money": "QUITAR DINERO",
    "editor.node.animation": "ANIMACIÓN",
    "editor.node.wait": "ESPERAR",
    "editor.node.random": "ALEATORIO",
    "editor.node.teleport": "TELETRANSPORTE",
    "editor.node.npc_change": "CAMBIAR NPC",
    "editor.node.sound": "SONIDO",

    "editor.cat_flow": "Flujo",
    "editor.cat_dialogue": "Diálogo",
    "editor.cat_logic": "Lógica",
    "editor.cat_economy": "Economía",
    "editor.cat_effects": "Efectos",
    "editor.search_nodes": "Buscar",
    "editor.hint_pan": "Mover lienzo",
    "editor.hint_search": "Buscar nodos",
    "editor.hint_delete": "Eliminar selección",
    "editor.hint_duplicate": "Duplicar",
    "editor.hint_auto_layout": "Auto organizar",
    "editor.auto_layout": "Auto Organizar",
    "editor.node_count": "nodos",
    "editor.conn_count": "enlaces",
    "editor.palette_placeholder": "Buscar un nodo...",
    "editor.palette_empty": "Ningún nodo coincide con tu búsqueda",
    "editor.palette_add": "Añadir",
    "editor.palette_close": "Cerrar",
    "editor.fit_view": "Ajustar Vista",
    "editor.duplicate": "Duplicar",
    "editor.event_server": "Lado servidor",
    "editor.event_payload": "Carga útil",

    "simulator.start": "Iniciar Simulación",
    "simulator.live_feed": "Señal en Vivo",
    "simulator.system": "SISTEMA",
    "simulator.memory_debug": "ESTADO DE MEMORIA (DEBUG)",
    "simulator.no_start_node": "No se encontró nodo START en el gráfico.",

    "editor.var.cat_memory": "Memoria",
    "editor.var.cat_item": "Ítems",
    "editor.var.cat_money": "Dinero",
    "editor.var.cat_job": "Trabajo / Grupo",
    "editor.var.cat_player": "Jugador",
    "editor.var.raw_key": "CLAVE",
    "editor.var.custom": "Variable Personalizada",
    "editor.var.custom_hint": "Variable establecida por un nodo SET_VARIABLE (almacenada en la memoria de interacción).",
    "editor.var.has_item": "Tiene Ítem (cantidad)",
    "editor.var.has_item_hint": "Cantidad de este ítem en el inventario del jugador. Escribe el nombre del ítem abajo.",
    "editor.var.money_cash": "Efectivo",
    "editor.var.money_cash_hint": "Cantidad de efectivo que tiene el jugador.",
    "editor.var.money_bank": "Banco",
    "editor.var.money_bank_hint": "Cantidad de dinero en la cuenta bancaria del jugador.",
    "editor.var.has_job": "Tiene Trabajo / Grupo",
    "editor.var.has_job_hint": "Comprueba si el jugador pertenece a este trabajo o grupo. Escribe el nombre del trabajo abajo.",
    "editor.var.player_health": "Salud",
    "editor.var.player_health_hint": "Salud del jugador (100-200). 100 = muerto, 200 = salud completa.",
    "editor.var.player_armor": "Armadura",
    "editor.var.player_armor_hint": "Valor de armadura del jugador (0-100).",
    "editor.var.player_stamina": "Resistencia",
    "editor.var.player_stamina_hint": "Resistencia de sprint restante (0-100).",
    "editor.var.player_is_dead": "Está Muerto",
    "editor.var.player_is_dead_hint": "1 si el jugador está muerto, 0 en caso contrario.",
    "editor.var.player_is_wanted": "Nivel de Búsqueda",
    "editor.var.player_is_wanted_hint": "Nivel de búsqueda policial (0-5).",
    "editor.var.player_in_vehicle": "En Vehículo",
    "editor.var.player_in_vehicle_hint": "1 si el jugador está en un vehículo, 0 en caso contrario.",
    "editor.var.player_speed": "Velocidad (km/h)",
    "editor.var.player_speed_hint": "Velocidad de movimiento actual en km/h.",
    "editor.var.player_weapon": "Arma Actual",
    "editor.var.player_weapon_hint": "Hash del arma equipada actualmente.",
    "editor.var.player_is_swimming": "Está Nadando",
    "editor.var.player_is_swimming_hint": "1 si el jugador está nadando, 0 en caso contrario.",
    "editor.var.player_is_falling": "Está Cayendo",
    "editor.var.player_is_falling_hint": "1 si el jugador está cayendo, 0 en caso contrario.",
    "editor.var.player_is_running": "Está Corriendo",
    "editor.var.player_is_running_hint": "1 si el jugador está corriendo, 0 en caso contrario.",
    "editor.var.player_name": "Nombre del Personaje",
    "editor.var.player_name_hint": "Nombre completo (nombre + apellido) del framework.",
    "editor.var.player_job_name": "Nombre del Trabajo",
    "editor.var.player_job_name_hint": "Nombre del trabajo actual del jugador (ej. 'police', 'mechanic').",
    "editor.var.player_job_grade": "Grado del Trabajo",
    "editor.var.player_job_grade_hint": "Nivel numérico del grado del trabajo actual del jugador.",
    "editor.var.player_gang_name": "Nombre de la Banda",
    "editor.var.player_gang_name_hint": "Nombre de la banda del jugador (solo QBCore, 'none' en ESX).",
    "editor.var.player_citizenid": "ID Ciudadano",
    "editor.var.player_citizenid_hint": "Identificador único del personaje.",
    "editor.var.player_gender": "Género",
    "editor.var.player_gender_hint": "0 = masculino, 1 = femenino (depende del framework).",
    "editor.var.player_phone_number": "Número de Teléfono",
    "editor.var.player_phone_number_hint": "Número de teléfono del personaje.",
    "editor.value_mode_fixed": "Valor fijo",
    "editor.value_mode_var": "Comparar contra otra variable"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key as keyof typeof translations['en']] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
